spring.application.name=Task-Managment-Kafka-React
# ==============================================
# MongoDB
# ==============================================
spring.mongodb.uri=mongodb://localhost:27017/taskDB
spring.mongodb.database=taskDB

# ==============================================
# Kafka ? broker + consumer group only
# All serializer config is in KafkaConfig.java
# ==============================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=task-management-group
spring.kafka.admin.fail-fast=false
spring.kafka.admin.properties.request.timeout.ms=30000

# ==============================================
# Kafka Topic
# ==============================================
kafka.topic.name=task-events

# ==============================================
# Jackson
# ==============================================
spring.jackson.deserialization.fail-on-unknown-properties=false

# ── Keycloak JWT Resource Server ────────────────────────────
# Spring Security fetches OIDC config from Keycloak at startup
# issuer-uri = Keycloak URL from INSIDE Docker network
spring.security.oauth2.resourceserver.jwt.issuer-uri=\
   http://localhost:8180/realms/internship-task-realm
#http://keycloak:8180/realms/internship-task-realm

# JWK set URI — alternative if issuer-uri causes startup order issues
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=\
    http://localhost:8180/realms/internship-task-realm/protocol/openid-connect/certs
  #http://keycloak:8180/realms/internship-task-realm/protocol/openid-connect/certs

# ── CORS ─────────────────────────────────────────────────────
# Allow React frontend (running in Docker on port 3000) to call the backend
cors.allowed-origins=http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.allow-credentials=true
